/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client03)
#  Generated on:      Thu Sep  5 20:59:08 2019
#  Design:            notGate
#  Command:           saveNetlist notGate-innovus-netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 12:06:34 IST (Sep  5 2019 06:36:34 UTC)
// Verification Directory fv/notGate 
module notGate (
	x, 
	op);
   input x;
   output op;

   INVXL g2 (.A(x),
	.Y(op));
endmodule

