
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 11:12:37 IST (Sep  5 2019 05:42:37 UTC)

// Verification Directory fv/andGate 

module andGate(x, y, op);
  input x, y;
  output op;
  wire x, y;
  wire op;
  AND2XL g8(.A (y), .B (x), .Y (op));
endmodule

