/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client02)
#  Generated on:      Thu Sep  5 14:48:01 2019
#  Design:            xorGate
#  Command:           saveNetlist xorGate-innovus-netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 12:09:34 IST (Sep  5 2019 06:39:34 UTC)
// Verification Directory fv/xorGate 
module xorGate (
	x, 
	y, 
	op);
   input x;
   input y;
   output op;

   CLKXOR2X1 g15 (.A(y),
	.B(x),
	.Y(op));
endmodule

