
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 12:09:34 IST (Sep  5 2019 06:39:34 UTC)

// Verification Directory fv/xorGate 

module xorGate(x, y, op);
  input x, y;
  output op;
  wire x, y;
  wire op;
  CLKXOR2X1 g15(.A (y), .B (x), .Y (op));
endmodule

