
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 17:15:17 IST (Sep  4 2019 11:45:17 UTC)

// Verification Directory fv/andGate 

module andGate(x, y, op);
  input x, y;
  output op;
  wire x, y;
  wire op;
  AND2XL g8(.A (y), .B (x), .Y (op));
endmodule

