/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client03)
#  Generated on:      Thu Sep  5 18:23:30 2019
#  Design:            orGate
#  Command:           saveNetlist orGate-innovus-netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 17:04:59 IST (Sep  5 2019 11:34:59 UTC)
// Verification Directory fv/orGate 
module orGate (
	x, 
	y, 
	op);
   input x;
   input y;
   output op;

   OR2X1 g2 (.A(y),
	.B(x),
	.Y(op));
endmodule

