
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 12:06:34 IST (Sep  5 2019 06:36:34 UTC)

// Verification Directory fv/notGate 

module notGate(x, op);
  input x;
  output op;
  wire x;
  wire op;
  INVXL g2(.A (x), .Y (op));
endmodule

