
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 12:05:01 IST (Sep  5 2019 06:35:01 UTC)

// Verification Directory fv/norGate 

module norGate(x, y, op);
  input x, y;
  output op;
  wire x, y;
  wire op;
  NOR2XL g10(.A (y), .B (x), .Y (op));
endmodule

