
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 17:04:59 IST (Sep  5 2019 11:34:59 UTC)

// Verification Directory fv/orGate 

module orGate(x, y, op);
  input x, y;
  output op;
  wire x, y;
  wire op;
  OR2X1 g2(.A (y), .B (x), .Y (op));
endmodule

