/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client02)
#  Generated on:      Thu Sep  5 12:56:34 2019
#  Design:            andGate
#  Command:           saveNetlist andGate-innovus-netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 11:12:37 IST (Sep  5 2019 05:42:37 UTC)
// Verification Directory fv/andGate 
module andGate (
	x, 
	y, 
	op);
   input x;
   input y;
   output op;

   AND2XL g8 (.A(y),
	.B(x),
	.Y(op));
endmodule

