
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 12:13:32 IST (Sep  5 2019 06:43:32 UTC)

// Verification Directory fv/nandGate 

module nandGate(x, y, op);
  input x, y;
  output op;
  wire x, y;
  wire op;
  NAND2XL g4(.A (y), .B (x), .Y (op));
endmodule

