/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client02)
#  Generated on:      Thu Sep  5 13:53:10 2019
#  Design:            nandGate
#  Command:           saveNetlist nandGate-innovus-netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 12:13:32 IST (Sep  5 2019 06:43:32 UTC)
// Verification Directory fv/nandGate 
module nandGate (
	x, 
	y, 
	op);
   input x;
   input y;
   output op;

   NAND2XL g4 (.A(y),
	.B(x),
	.Y(op));
endmodule

