/*
###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID client03)
#  Generated on:      Thu Sep  5 20:15:26 2019
#  Design:            xnorGate
#  Command:           saveNetlist xnorGate-innovus-netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  5 2019 12:10:52 IST (Sep  5 2019 06:40:52 UTC)
// Verification Directory fv/xnorGate 
module xnorGate (
	x, 
	y, 
	op);
   input x;
   input y;
   output op;

   // Internal wires
   wire n_0;

   OAI21XL g17 (.A0(x),
	.A1(y),
	.B0(n_0),
	.Y(op));
   NAND2XL g18 (.A(y),
	.B(x),
	.Y(n_0));
endmodule

