
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Sep  4 2019 19:39:17 IST (Sep  4 2019 14:09:17 UTC)

// Verification Directory fv/f1 

module f1(a, b, c, d, op);
  input a, b, c, d;
  output op;
  wire a, b, c, d;
  wire op;
  AO22X1 g17(.A0 (d), .A1 (c), .B0 (b), .B1 (a), .Y (op));
endmodule

